node('.net')
{
    try 
    {
        def image
        stage ('Checkout source code') 
        {
            echo("Code checkout...")           
            git(branch: "develop", credentialsId: "74517f2b-b853-4bb3-bf6a-b8229150b394", url: "https://github.com/termitos/CoreWebApi.git")
        } 
        stage('Restore dependencies') 
        {
            echo("Restoring dependencies...")
            sh("dotnet restore")
        }
        stage('Build source code') 
        {
            echo("Compiling the solution...")
            sh("dotnet build --configuration Release --version-suffix DEV-${env.BUILD_NUMBER}")
        }
        stage('Publish package') 
        {
            echo("Creating pulbish directory...")
            dir("CoreWebApi")
            {
                sh("dotnet build --configuration Release --version-suffix DEV-${env.BUILD_NUMBER}")
                sh("dotnet publish --no-restore --no-build --configuration Release --output publish")
            }
        }
		stage('Build docker image')
		{
			echo("Building docker image...")
            dir("CoreWebApi")
            {
				image = docker.build("corewebapi:DEV-${env.BUILD_NUMBER}")
			}
		}
        stage('Push docker image ') {
            echo "Push docker image to ECR repository"
            docker.withRegistry('https://524548625119.dkr.ecr.eu-west-3.amazonaws.com/corewebapi', 'aws-access-credentials') 
            {
                image.push("DEV-${env.BUILD_NUMBER}")
            }
        }
    } 
    catch (Exception err) 
    {
        currentBuild.result = 'FAILURE'
        echo("Error message: $err.message")
        notifyFailure()
    }
    finally
    {
        cleanWs(cleanWhenAborted: false, cleanWhenFailure: false)        
    }
}

def notifySuccessful()
{    
    emailext (
        subject: "SUCCESSFUL: Job ${env.JOB_NAME} [${env.BUILD_NUMBER}]",
        body: "SUCCESSFUL: Job ${env.JOB_NAME} [${env.BUILD_NUMBER}]: Check console output at ${env.BUILD_URL}",
        recipientProviders: [developers()]
    )
}

def notifyFailure() 
{
    emailext (
        subject: "FAILED: Job ${env.JOB_NAME} [${env.BUILD_NUMBER}]",
        body: "FAILED: Job ${env.JOB_NAME} [${env.BUILD_NUMBER}]: Check console output at ${env.BUILD_URL}",
        recipientProviders: [developers()]
    )
}